# This is a basic workflow to help you get started with Actions
name: UPDATE HICH GLOBAL

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: pull on server
        run: git pull

